[package]
name = "lp5018"
version = "0.1.0"
authors = ["Robert Hanyecz <rh@wertschuetz.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = "0.2.5"
